### ISSUE TITLE
Home, Ledger, and Reports Menu

### ISSUE THREAD

**Issue by soulsequence** [Phini0n/FinancialTracker#8]
> As a User, I want to have a Home Menu, Ledger Menu, and Reports Menu so that I can access the relevant transaction information with little to no confusion.

Filter Menu in a way that looks pleasing to the user and easy to understand.

- [x] Home Menu
- [x] Ledger Menu
- [x] Reports Menu

**Comment by Phini0n** [comment]
- [ ] Home Menu
- [ ] Ledger Menu
- [ ] Reports Menu

**Comment by soulsequence** [comment]
> As a user I want to have a home menu so I can access all of the program's main functionality.

Home

- [x] Looks
- [x] Function

**Comment by soulsequence** [comment]
> As a user I want to have a Ledger menu so that I can list my transactions.

Ledger

- [x] Looks
- [x] Function

**Comment by soulsequence** [comment]
> As a user I want to have a reports menu so that I can further specify how I want ledger information to be filtered.

Reports

- [x] Looks
- [x] Function
